### ISSUE TITLE
Incorrect form fields configuration

### ISSUE THREAD

**Issue by iamsaint** [yiisoft/yii-form#9]
There is no check for the existence of a attribute when configuring a widget

For example this code should throw exception 

`
(new TextInput)->config($formModel, 'undefined_form_attribute')
`

**Comment by terabytesoftw** [comment]
Of course you are just creating the object you are not rendering it.

```php
(new TextInput)->config($data, 'undefined_form_attribute')->run();

TextInput::widget()->config($data, 'undefined_form_attribute')->run();
```

1) Yiisoft\Form\Tests\Widget\NoExistTest::test                                                                                                                                                  Undefined property: Yiisoft\Form\Tests\Stub\PersonalForm::$undefined_form_attribute

**Comment by iamsaint** [comment]
Please reopen issue.  In you described cases widget still no throws exception for undefined field

```php
class LoginForm extends FormModel {
    private ?string $login;
    private ?string $password;
    /* ...  */
}
```

```php
echo (new TextInput)->config($formModel, 'login')->run();
echo (new PasswordInput)->config($formModel, 'password')->run();
echo (new TextInput)->config($formModel, 'undefined_form_attribute')->run();
```

in html i got this

```html
<input type="text" id="login" name="login">
<input type="password" id="password" name="password">
<input type="text" id="undefined_form_attribute" name="undefined_form_attribute">
```

**Comment by rustamwin** [comment]
@terabytesoftw tests do not exist for undefined form field

**Comment by terabytesoftw** [comment]
> Please reopen issue. In your described cases widget still no throws exception for undefined field
> 
> ```
> class LoginForm extends FormModel {
>     private ?string $login;
>     private ?string $password;
>     /* ...  */
> }
> ```
> 
> ```
> echo (new TextInput)->config($formModel, 'login')->run();
> echo (new PasswordInput)->config($formModel, 'password')->run();
> echo (new TextInput)->config($formModel, 'undefined_form_attribute')->run();
> ```
> 
> in html i got this
> 
> ```
> <input type="text" id="login" name="login">
> <input type="password" id="password" name="password">
> <input type="text" id="undefined_form_attribute" name="undefined_form_attribute">
> ```

You can put all the code to reproduce the error clearly you must have some problem in your php configuration, I already added the exception but it is redundant all the widgets use getAttributeValue(), and when looking to return the value of the property it should throw the error because it does not exists.

https://github.com/yiisoft/yii-form/blob/b18bc146c897145542a4dbd94bb2e8f20bb447d3/src/FormModel.php#L289

I still wonder why it does not generate the error, if it is tested.

https://github.com/yiisoft/yii-form/blob/b18bc146c897145542a4dbd94bb2e8f20bb447d3/tests/FormModelTest.php#L31

**Comment by terabytesoftw** [comment]
> Las pruebas @terabytesoftw no existen para el campo de formulario indefinido

https://github.com/yiisoft/yii-form/blob/b18bc146c897145542a4dbd94bb2e8f20bb447d3/tests/FormModelTest.php#L31

I don't need to test the widget because it is clearly tested in the FormModel.

**Comment by rustamwin** [comment]
@terabytesoftw I meant this test:
> Yiisoft\Form\Tests\Widget\NoExistTest::test Undefined property: Yiisoft\Form\Tests\Stub\PersonalForm::$undefined_form_attribute

as you said above.
